// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAanU-ygrgR9RdPj_ZPBJ10KV02gxk098k',
    appId: '1:848570536552:web:4fe6f7c771c79b9ce561dd',
    messagingSenderId: '848570536552',
    projectId: 'ewallet-eb2ed',
    authDomain: 'ewallet-eb2ed.firebaseapp.com',
    storageBucket: 'ewallet-eb2ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtAK7l89KqiqTnquIga3BL4ydowQYsETo',
    appId: '1:848570536552:android:2c4317f9dd0f286de561dd',
    messagingSenderId: '848570536552',
    projectId: 'ewallet-eb2ed',
    storageBucket: 'ewallet-eb2ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpftfAIAIqKi9rmBgrqvbBEvlMDQqDu4E',
    appId: '1:848570536552:ios:a7d53573af67541ee561dd',
    messagingSenderId: '848570536552',
    projectId: 'ewallet-eb2ed',
    storageBucket: 'ewallet-eb2ed.appspot.com',
    iosBundleId: 'com.example.ewallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpftfAIAIqKi9rmBgrqvbBEvlMDQqDu4E',
    appId: '1:848570536552:ios:a7d53573af67541ee561dd',
    messagingSenderId: '848570536552',
    projectId: 'ewallet-eb2ed',
    storageBucket: 'ewallet-eb2ed.appspot.com',
    iosBundleId: 'com.example.ewallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAanU-ygrgR9RdPj_ZPBJ10KV02gxk098k',
    appId: '1:848570536552:web:c40a76656dd32c23e561dd',
    messagingSenderId: '848570536552',
    projectId: 'ewallet-eb2ed',
    authDomain: 'ewallet-eb2ed.firebaseapp.com',
    storageBucket: 'ewallet-eb2ed.appspot.com',
  );

}